---
- name: create /etc/certificates directory
  file: path=/etc/certificates state=directory owner=root group=root mode=744

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN={( ansible_fqdn )}" -days 3650 -keyout /etc/certificates/server.key -out /etc/certificates/server.crt -extensions v3_ca creates=/etc/certificates/server.crt

